/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/netbirdio/netbird/client/harmony */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "client_settings.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "nbharmony.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "sso.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* NbCoreSetClientSettings(char* settingsJSON);
extern char* NbCoreInit(char* deviceName, char* osVersion, char* configJSON);
extern char* NbCoreStorePrivateCredentialImport(char* credentialFilePath, char* setupKey, char* managementURL, char* managementDialAddress);
extern char* NbCoreStartPrivateAuthentication(char* deviceName, char* osVersion, char* configFilePath, char* credentialFilePath);
extern char* NbCoreSetConfig(char* configJSON);
extern char* NbCoreSetPlatformState(int tunFD, int vpnExtensionReady, int processProtectReady, int dnsReady, int networkChangeReady, char* lastError);
extern char* NbCoreClearPlatformState(void);
extern char* NbCoreSetInterfaces(char* interfacesJSON);
extern char* NbCorePlatformSnapshot(void);
extern char* NbCoreStartPreparation(char* stateFilePath, char* cacheDir, char* logFilePath);
extern char* NbCoreProvideTunFD(int tunFD);
extern char* NbCoreDebugRequestReconfiguration(void);
extern char* NbCoreBeginReconfiguration(unsigned long long generation, unsigned long long targetRevision);
extern char* NbCoreRestartPreparation(unsigned long long generation, char* stateFilePath, char* cacheDir, char* logFilePath);
extern char* NbCoreProvideTunFDForGeneration(int tunFD, unsigned long long preparationGeneration, unsigned long long reconfigurationGeneration, unsigned long long configRevision);
extern char* NbCorePlatformRollback(void);
extern char* NbCorePlatformSelfTest(void);
extern char* NbCoreStatus(void);
extern char* NbCoreConnect(void);
extern char* NbCoreShutdown(void);
extern char* NbCoreSelfTest(void);
extern char* NbCoreTunSelfTest(void);
extern char* NbCoreResetTunRuntimeStats(void);
extern char* NbCoreTunRuntimeStats(void);
extern void NbFreeString(void* value);
extern char* NbCoreStartSSOLogin(char* deviceName, char* osVersion, char* configFilePath, char* managementURL, int preferDeviceCode);
extern char* NbCoreCancelSSOLogin(void);

#ifdef __cplusplus
}
#endif
